
services:
  fastapi:
    build:
      context: .
    # image: miapi:1.0.0
    ports:
      - "8000:8000"  
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

  ms-express:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Apocalypse117
      - MSSQL_PID=Express
    ports:
      - "1435:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./database-users.sql:/database-users.sql

  db-init:
    image: mcr.microsoft.com/mssql-tools
    volumes:
      - ./database-users.sql:/database-users.sql
    entrypoint: ["/bin/bash", "-c"]
    command:
      - /opt/mssql-tools/bin/sqlcmd -S ms-express -U sa -P Apocalypse117 -i /database-users.sql
    restart: "no"

volumes:
  mssql-data:
